              <option value="1">clientèle</option>
              <option value="2">Facturation </option>
              <option value="3">Recouvrement</option>
              <option value="4">Paiement</option>
              <option value="5">Releveur</option>
              <option value="6">Resp Caisse</option>
              <option value="7">Admin Systeme</option>
              <option value="8">Resp Facturation</option>
              <option value="9">Resp Recouvrement </option> 
              <option value="10">TInformatique</option>
              <option value="20">Comptabilite</option>
              <option value="30">Commmunication</option>
              <option value="40">Approvisionnement</option>  
              <option value="41">Gaz</option>  
              <option value="42">Devis & Branchement</option> 
              <option value="43">Resp Commercial</option>
              <option value="44">Serv Controle</option> 
              <option value="45">Magasin</option>  
              <option value="46">Admin Commercial</option> 
			  <option value="47">Laboratoire</option> 
              <option value="50">Serv Personnel</option>
              <option value="60">Serv Distribution</option>
              <option value="70">Serv Production</option>
              <option value="80">Statistique</option> 
              <option value="90">R & D </option>  
			  <option value="91">Suivi MT et plus</option>  